[package]
name = "rust-tide-server"
version = "0.1.0"
authors = ["Anton Whalley <anton@venshare.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tide = { version = "0.8" }
async-std = { version = "1" }
application = { package = "rust-tide-default", path = "/project/user-app"}